### ISSUE TITLE
Cannot declare class

### ISSUE THREAD

**Issue by romamajestik** [tecsin/yii2-tinymce#1]
hi
For the `phpseclib` we need to put - `mbstring.func_overload = 0`
After which an error occurs - `Cannot declare class tecsin\tinymce\Tinymce because the name is already in use`

Do for example so `use dosamigos\tinymce\TinyMce as SomeMce;`

**Comment by onyijne** [comment]
Thank you, it has been implemented and version 1.0.1 rolled out to that effect.
